# Generated by Django 5.0.1 on 2024-01-15 11:18

import dispatch.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='departure',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='destination',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('ACTIVE', 'Active'), ('DISPATCHED', 'Dispatched'), ('DELIVERY', 'Delivered')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=dispatch.models.item_images),
        ),
        migrations.CreateModel(
            name='ItemTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('updated_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Select Status'), ('ACTIVE', 'Active'), ('DISPATCHED', 'Dispatched'), ('DELIVERY', 'Delivered')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=5000, null=True)),
                ('notes', models.CharField(blank=True, max_length=5000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_tracker', to='dispatch.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
