# Generated by Django 5.0.1 on 2024-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_item_departure_item_destination_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimate Time in(Minutes)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='departure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
