# Generated by Django 5.0.1 on 2024-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_item_estimated_time_alter_item_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtracker',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
