# Generated by Django 5.0.1 on 2024-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_alter_item_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtracker',
            name='date',
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
