# Generated by Django 5.0.1 on 2024-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
